<?
$PERM["catalog1"]["2"]="R";
$PERM["personal"]["7"]="W";
$PERM["catalog"]["7"]="W";
$PERM["news"]["7"]="W";
$PERM["about"]["7"]="W";
$PERM["index.php"]["7"]="W";
$PERM["admserv"]["*"]="D";
$PERM["admserv"]["6"]="X";
$PERM["admserv"]["7"]="X";
$PERM["/"]["*"]="R";
?>