<?require($_SERVER["DOCUMENT_ROOT"]."/bitrix/header.php");?>
<?$APPLICATION->IncludeComponent("MP:catalog", "monplaisir", array(
	"IBLOCK_TYPE" => "catalog",
	"IBLOCK_ID" => "2",
	"IBLOCK_CODE" => "mebel",
	"HIDE_NOT_AVAILABLE" => "N",
	"SECTION_ID_VARIABLE" => "SECTION_CODE",
	"SEF_MODE" => "Y",
	"SEF_FOLDER" => "/catalog/",
	"CACHE_TYPE" => "A",
	"CACHE_TIME" => "36000000",
	"CACHE_FILTER" => "N",
	"CACHE_GROUPS" => "Y",
	"SET_TITLE" => "Y",
	"SET_STATUS_404" => "Y",
	"USE_ELEMENT_COUNTER" => "N",
	"USE_FILTER" => "N",
	"FILTER_NAME" => "",
	"FILTER_PROPERTY_CODE" => array(
		0 => "COLORS",
		1 => "MATHERIALS",
	),
	"FILTER_PRICE_CODE" => array(
		0 => "ROZNICA",
	),
	"COLORS_COUNT" => 10,
	"COLORS_IMG_SIZE" => 20,
	"USE_COMPARE" => "Y",
	"PRICE_CODE" => array(
		0 => "ROZNICA",
		1 => "GROSS",
	),
	"USE_PRICE_COUNT" => "N",
	"SHOW_PRICE_COUNT" => "0",
	"PRICE_VAT_INCLUDE" => "Y",
	"PRICE_VAT_SHOW_VALUE" => "N",
	"CONVERT_CURRENCY" => "Y",
	"CURRENCY_ID" => "RUB",
	"BASKET_URL" => "/personal/cart.php",
	"ACTION_VARIABLE" => "action",
	"PRODUCT_ID_VARIABLE" => "id",
	"USE_PRODUCT_QUANTITY" => "N",
	"ADD_PROPERTIES_TO_BASKET" => "Y",
	"PRODUCT_PROPS_VARIABLE" => "prop",
	"PARTIAL_PRODUCT_PROPERTIES" => "N",
	"PRODUCT_PROPERTIES" => array(
		0 => "COLORS",
		1 => "MATHERIALS",
	),
	"PAGE_ELEMENT_COUNT" => "30",
	"LIST_PROPERTY_CODE" => array(
		0 => "NEWPRODUCT",
		1 => "SALELEADER",
		2 => "SPECIALOFFER",
		3 => "",
	),
	"INCLUDE_SUBSECTIONS" => "Y",
	"DETAIL_PROPERTY_CODE" => array(
		0 => "COLORS",
		1 => "MATHERIALS",
	),
	"USE_ALSO_BUY" => "Y",
	"ALSO_BUY_ELEMENT_COUNT" => "5",
	"ALSO_BUY_MIN_BUYES" => "2",
	"PRODUCT_QUANTITY_VARIABLE" => "quantity",
	"SEF_URL_TEMPLATES" => array(
		"sections" => "",
		"section" => "#SECTION_CODE#/",
		"element" => "#SECTION_CODE#/#ELEMENT_ID#/",
		"compare" => "compare.php?action=#ACTION_CODE#",
	),
	"VARIABLE_ALIASES" => array(
		"compare" => array(
			"ACTION_CODE" => "action",
		),
	),
	false
	)
);?><?require($_SERVER["DOCUMENT_ROOT"]."/bitrix/footer.php");?>