<?
return array(
	"bxe-first-letter" => "",
	"bxe-quote" => "",
	"blockquote" => "",
	"lead" => "",
	"bg-primary" => "",
	"bg-success" => "",
	"bg-info" => "",
	"bg-warning" => "",
	"bg-danger" => "",
	"alert alert-success" => "",
	"alert alert-info" => "",
	"alert alert-warning" => "",
	"alert alert-danger" => "",
	"alert alert-note" => "",
	"alert alert-sys" => "",
	"alert bxe-icon alert-success" => "",
	"alert bxe-icon alert-info" => "",
	"alert bxe-icon alert-warning" => "",
	"alert bxe-icon alert-danger" => "",
	"alert bxe-icon alert-note" => "",
	"alert bxe-icon alert-sys" => "",
	"ul" => "",
	"bxe-list bxe-lis-blue~~fa fa-check-square" => "",
	"bxe-list bxe-lis-blue~~fa fa-check" => "",
	"bxe-list bxe-lis-blue~~fa fa-minus" => "",
	"bxe-list bxe-lis-blue~~fa fa-map-marker" => "",
	"bxe-list bxe-lis-blue~~fa fa-rocket" => "",
	"bxe-list bxe-lis-blue~~fa fa-paw" => "",
	"bxe-list bxe-lis-blue~~fa fa-paper-plane" => "",
	"bxe-list bxe-lis-blue~~fa fa-certificate" => "",
	"bxe-list bxe-lis-blue~~fa fa-flag" => "",
	"bxe-list bxe-lis-blue~~fa fa-bomb" => "",
	"bxe-list bxe-lis-blue~~fa fa-close" => "",
	"bxe-list bxe-lis-blue~~fa fa-star" => "",
	"bxe-list bxe-lis-blue~~fa fa-times-circle" => "",
	"bxe-list bxe-lis-blue~~fa fa-caret-square-o-right" => "",
	"bxe-list bxe-lis-blue~~fa fa-heart" => "",
);
?>